version: '3.3'
services:
  db:
    image: mysql:latest
    container_name: mysql-db2
    restart: on-failure
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=fileDb
      - MYSQL_ROOT_USER=root
    healthcheck:
      test: "mysqladmin ping -u root -p$${MYSQL_ROOT_PASSWORD}"
      interval: 10s
      timeout: 30s
      retries: 3

  file-service:
    image: file-service-manager
    restart: always
    container_name: file-service-manager
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    links:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db2:3306/customer?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: fileDb



