spring:
  application:
    name: file-api
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://mysql-db2:3306/fileDb?characterEncoding=UTF-8&serverTimezone=UTC&createDatabaseIfNotExist=true

app:
  jwt:
    # echo -n "somevalue" | openssl sha512 -hmac "somekey"
    secret: 0ddf5597e02d981f8803c4cc11f015a4e52679d706edb29b595d9e466def5bcf95273a3053ab5d97ee893c23e4023b912daefaade316406a33b7685d4d223dfa
    expiration:
      minutes: 10
  cors:
    allowed-origins: http://localhost:3000


file:
  uploadDirectory: /Users/uploadFile
